### ISSUE TITLE
Working test build of site with new template

### ISSUE THREAD

**Issue by Andy-ABTec** [Andy-ABTec/minimal-mistakes#1]
@MarkSummerville, @JoeBiellik...
Finally got the dam thing up and running...
Scales nicely with the browser window size...
Slowly copying content across and re-working all the graphics...
I think the logo needs to be a little bigger, and I need to do the home/no-horizontal hold thing
Thoughts?

https://andy-abtec.github.io/minimal-mistakes

_Also need to replace some of the hard coding (esp. in the footer) with liquid._

**Comment by JoeBiellik** [comment]
Looking good!

I agree the header logo could be bigger, at 75px wide with -0.5rem vertical padding.

**Comment by Andy-ABTec** [comment]
I tend to agree, but it may need to be a little bigger than 75px so I can squeeze the word "Home" onto the screen and it be noticable

**Comment by JoeBiellik** [comment]
Is the sidebar menu ment to be on the left on the [options page](https://andy-abtec.github.io/minimal-mistakes/manual/options/) etc?

**Comment by Andy-ABTec** [comment]
Absolutely, I'm working on the sidebar menus at the moment, the documentation makes it interesting to say the least!

**Comment by Andy-ABTec** [comment]
Woohoo! checkout https://andy-abtec.github.io/minimal-mistakes/manual/quickstart/ and try shrinking your browser with an image on the screen - COOL!

**Comment by Andy-ABTec** [comment]
Its getting there...

Download, Quick-Start Guide, User Guide & Options and Preferences getting verrrrrrry close - just need a few more tweaks

**Comment by MarkSummerville** [comment]
Looks good on mobile too. Am away from the office, so only way to see it atm.  Still looks good

**Comment by Andy-ABTec** [comment]
Been playing with the "homepage" all day - template is now called "not-so-minimal-mistakes".

Having issues with _config.yml contents not being ignored when it's listed in .gitignore (which hasn't helped).

Still, I got there in the end, the masthead download link and download button are now dynamic, linked to the github api. The version number in the page lead is also dynamic from the github api.

Not bad considering I knew zip about jquery at 9:00 this morning 😎

**Comment by MarkSummerville** [comment]
Hi, 

Looks really good.  Thanks for throwing yourself headlong into the new theme. I have one main observation though:
It feels like we have too many top level menu items. Part of the point of moving to this theme was the improved navigation it offered. Even on my wide monitor the 'Help and Support' link is hidden behind the menu. How about rationalising to: About: Download: User Guide: Help & Support. I look at 'Information Architecture' for websites as part of my day job and part of that is thinking about the audiences. In my head there are a few: 

  1. Someone browsing trying to choose whether this is the right tool for them. (this is an audience we under represent at the moment. When I get some tome I'll create some content. They are interested in features, compatibility and mainly screenshots). We could look to do a feature comparison with competitors here.  (Might be tricky, but it is that sort of thing) Their end goal is a download of the tool. 
  2. the next audience is a new user who wants to setup the system and wants details on what all the options do. Core quickstart / user guide stuff.  We deal with these people well 
 3. is someone having  a problem so they need some steps to help them solve issues  (looking at logs, forums etc) and then be directed to support if they still need it.
  4. is someone who wants to help - really we get this person by directing them to GitHub and/or the forums which I think we already have covered

To do this I would propose:
   * Quick start, user guide, options, tools and 'The Command line' all become part of user guide pages (we can still have multiple physical pages in this area)
   * Config Files / Logging becomes part of help & support
   * 'What can I do to help' would go under 'About'

I am happy to do this in another fork/branch so we can compare / contrast.  Thoughts?

**Comment by MarkSummerville** [comment]
PS see https://kodi.tv/about for an example of the sort of thing I'm thinking to help audience 1 above

**Comment by MarkSummerville** [comment]
Also - thinking about it. We could remove the 'download' menu option. We have the link on the homepage and we'd put the link all over the 'about' page. If someone is on the manual/quick start/support pages then they already have the software and have no need to download it.

**Comment by Andy-ABTec** [comment]
Feel free to modify this one if you wish (or pull a copy). I have a backup and a local copy in my development environment (integrated is a step too far!)

The original structure was based on the menu structure of the prog, I really just wanted to get the jQuery/liquid/jekyll sorted out Feel free to change as you wish but I need to know where we're going otherwise I won't be much help.

As it stands I think the old site was "prettier" this seems rather bland and clinical.

From what I can tell search only works in blog pages, not docs or manual so that's a no-no for now

Could move the quickstart  link into a splash screen teaser - are you still planning to link it from the help menu?

**Comment by Andy-ABTec** [comment]
A bit of color works wonders...

http://test.ab-tec.co.uk

How attached are you to that old telly?

**Comment by MarkSummerville** [comment]
Not attached to the telly at all - just tried to find something 'moody' to fit in with the theme!

Just thought I'd share some of the other sites I'm looking at when thinking about design. 
https://getbootstrap.com/docs/3.3/
https://getpocket.com/
https://kodi.tv/
https://evernote.com/
https://feedly.com/i/welcome
https://www.mozilla.org/en-US/firefox/new/

PS like the section below the 3 key features on the homepage. Feels like the right spot for it

**Comment by Andy-ABTec** [comment]
Figured it out last night, its getting there but the formatting is really
restrictive because the content has to be set in yaml front matter (can't
do ordered lists for example). Hopefully it'll look a bit better when I get
another block and a couple of images in there.

**Comment by Andy-ABTec** [comment]
You have a "Manual"

**Comment by Andy-ABTec** [comment]
Think this might be a bit closer to the goal post...

**Comment by MarkSummerville** [comment]
It looks really good - thanks again for your hard work.

**Comment by Andy-ABTec** [comment]
I sorted out how to update the template from an upstream repo late last night, so the template is up to date compared to the upstream repo mmistakes/minimal-mistakes.

Do you want to do anything with the footer?

**Comment by MarkSummerville** [comment]
I feel that we should do something with the footer. not sure what yet though. I'll have a think.

Jut doing a little testing:
 * Some of trhe links on 'support' are not formateed correctly eg "Visit the TV Rename Forum" at the end
 * LHS menu for 'Help' Relates to 'Tips & Tricks'
 * Menu options in the command line section are double indented

**Comment by Andy-ABTec** [comment]
Thanks for looking, been trying to spot everything on my own all week...

Fixed lhs menu for "Help and Support" -hangover from when I was "learning"
Fixed "Command Line" double indenting - hang over from when I was "learning"
Fixed typo on link - closing bracket in the wrong place,

**Comment by MarkSummerville** [comment]
Looks like a merge has gone wrong somewhere? Seem to be getting a few too many heading links in the top menu...

CHeers

**Comment by MarkSummerville** [comment]
also roadmap link on the help page

**Comment by MarkSummerville** [comment]
Looking good. Will have another read through tonight. Cheers
