### ISSUE TITLE
Update beta site to reflect changes in Options>Preferences>Scan Options

### ISSUE THREAD

**Issue by Andy-ABTec** [Andy-ABTec/minimal-mistakes#10]
Added new options for: -

Ignore Episodes Previously Seen
RSS manual scan only
JSON manual Scan oply
Auto Bulk Add on scan

**Comment by Andy-ABTec** [comment]
Completed

**Comment by Andy-ABTec** [comment]
@MarkSummerville please check and close if you're happy...

**Comment by MarkSummerville** [comment]
Have done a refactor of the preferences, so am in the process of tidying up the whole area.

**Comment by Andy-ABTec** [comment]
Let me know when you're done and I'll re-do all the screen grabs again.

**Comment by MarkSummerville** [comment]
Would welcome a second opinion. Are there any other locations that the preferences are illogical?

**Comment by Andy-ABTec** [comment]
Just downloading RC5, I'll take a look later...

**Comment by Andy-ABTec** [comment]
Looks ok to me - the info at the top of the panes helps...

You thinking about any more changes in the near future?

**Comment by Andy-ABTec** [comment]
@MarkSummerville, you've gone very quiet...

I note you've updated all the preferences images, do you want me to finish off the text?

**Comment by Andy-ABTec** [comment]
No worries, I think there's still a couple of preferences with little or no text. I'll sort them out and check the rest over the next few days...

**Comment by Andy-ABTec** [comment]
Updated "preferences-search-folders-01.png" and "preferences-search-folders-02.png" and updated image link in "Quickstart"

**Comment by Andy-ABTec** [comment]
Tweaked Preferences>General and added link to "Search Folders"

**Comment by Andy-ABTec** [comment]
Updated Preferences>Library Folders, added some links

**Comment by Andy-ABTec** [comment]
Updated Preferences>Files and Folders, added some links and expanded some of the explanations

**Comment by Andy-ABTec** [comment]
Updated Delete Folders and Media Center tabs

**Comment by Andy-ABTec** [comment]
Tweaked Media Centers tab

**Comment by Andy-ABTec** [comment]
Updated RSS/JSON and Torrentz/NZB tabs

**Comment by Andy-ABTec** [comment]
@MarkSummerville, I think that's all the "options" tidied up and the broken bits fixed - please check...

**Comment by MarkSummerville** [comment]
Looks great - thanks very much

We should probably explain the difference between the two sets of 'other file extensions'. I remember writing it in post somewhere - I'll dig it out

**Comment by Andy-ABTec** [comment]
Not wishing to chase, but did you find the post?

With that update done I can go back to sleep for a while 😃

**Comment by MarkSummerville** [comment]
Nah, couldn’t find it. Maybe I write it on the site somewhere? I’m getting
old

Basically. The ‘other extensions’  are used when renaming within the
library. The ‘keep together’ function is used when copying from the
download folder to the library. Some files, specifically nfo files, may be
treated differently in that they are not copied over (as tvr will create
them), but once created you want to keep them named the same

Make sense?

**Comment by Andy-ABTec** [comment]
Think this can be closed now...
