### ISSUE TITLE
Logo Switcher

### ISSUE THREAD

**Issue by Andy-ABTec** [Andy-ABTec/minimal-mistakes#2]
Hi @JoeBiellik, you know that offer of help you made?

I'm a bit stuck and could do with your experienced eyes...

I've cobbled some liquid together that switches the logo depending on the page for the new template
```
{% if page.url == '/' | page.url == absolute.url %}
    <img style="opacity: 0.5;" alt="Home button" src="{{ site.baseurl }}/assets/images/tv-static.png" />
{% else %}
    <a class="site-title" alt="Home Button" title="Return to Home Page" href="{{ '/' | absolute/.url }}"><img src="{{ site.baseurl }}/assets/images/tv-home.png" /></a>
{% endif %}  
```
Which appears to work quite happily, but highlights a problem with the template!
The masthead height changes between the index page and the manual pages which is causing a vertical shift in the image which spoils the effect...

Any ideas much appreciated...

You can find the code at the top of: 
```
https://andy-abtec.github.io/minimal-mistakes/includes/head/masthead.html
```
And will make you a collaborator if you need to play!

PS I know it's bad form to include style declarations inside tags, but it was quicker while I was messing around, I'll create a new class in the stylesheet once I know what's required...

Thanks again!

**Comment by Andy-ABTec** [comment]
Looks like padding on the image may have fixed it...

just need to sort out the liquid url's now.

**Comment by JoeBiellik** [comment]
Yes, padding is the way to handle this.

**Comment by Andy-ABTec** [comment]
I think the problem was triggered by the logo on the homepage being an img and the logo on the other pages being a link, it took quite a bit of poking about with inspect to get to the bottom of the differences and figure out what styles I needed to add to the img to bring it up to the same "size" as the link.

I think half the time just "talking" about stuff changes my perspective and is enough to wind me up and point me in the right direction...
