### ISSUE TITLE
Domain name testing

### ISSUE THREAD

**Issue by Andy-ABTec** [Andy-ABTec/minimal-mistakes#3]
Having got into a "bit of a pickle" last night when I discovered that whilst the site worked locally the navigation had broken url's on the gh-pages version; I think there are some issues with {{ liquid url's }} that need sorting out before this progresses too much further.

 Also we have no idea what else is going to break when domain redirection is applied on top.

To this end I've redirected "test.ab-tec.co.uk" to "andy-abtec.github.io" with my dns provider (will probably take about 24h) and tweaked the gh-pages settings to use the custom domain. 

At least we can test a full path once the changes take effect...

**Comment by Andy-ABTec** [comment]
Sorted, "http://test.ab-tec.co.uk" works fine - will leave it there for now...

**Comment by JoeBiellik** [comment]
When I go to [http://test.ab-tec.co.uk/](http://test.ab-tec.co.uk/) I don't get any CSS as the [file is loaded over HTTPS](https://test.ab-tec.co.uk/assets/css/main.css) and obviously, you don't have a certificate. I think you can go into the repo settings and disable HTTPS.

**Comment by Andy-ABTec** [comment]
Thought I already had - it works for me - I'll go check...

**Comment by Andy-ABTec** [comment]
No, definitely turned off, all the pages work for me over http with the css

**Comment by Andy-ABTec** [comment]
![image](https://user-images.githubusercontent.com/5175695/35474286-00242d38-0384-11e8-89ae-beff9be87c44.png)

**Comment by JoeBiellik** [comment]
I'm still getting most assets load over HTTPS in both Chrome and Firefox.

Warning triangle means it didn't load due to bad SSL cert:

![Shot](https://user-images.githubusercontent.com/43646/35474367-56ff8c5a-0385-11e8-9511-87f7eaf33810.png)

**Comment by Andy-ABTec** [comment]
I'm pretty sure it's something at the client end...
![image](https://user-images.githubusercontent.com/5175695/35474762-964389e8-038a-11e8-9c98-06ea1c18926c.png)

**Comment by JoeBiellik** [comment]
From your screenshot you are using HTTPS, not HTTP, so you wouldn't see the issue. You can see your browser shows the SSL is invalid ("Not secure").

**Comment by JoeBiellik** [comment]
I'm fairly sure you just need to change `[`https`` to ``http`` in the config](https://github.com/Andy-ABTec/minimal-mistakes/blob/gh-pages/_config.yml#L16) to fix this.

**Comment by Andy-ABTec** [comment]
Sorted thanks!
Typo on my part caused by frustration with git/github not honouring the content of .gitignore and insisting on changing my _config.yml file every time I pull or push. Grrrrr....

**Comment by JoeBiellik** [comment]
The [minimal-mistakes guide](https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#remove-the-unnecessary) explicitly says its okay to delete a few bits, might help. If you delete ``.editorconfig`` I'd strongly recommend you make your own new one.

**Comment by Andy-ABTec** [comment]
Already done, learnt that lesson with leap-day 8-)

**Comment by MarkSummerville** [comment]
Looks good to me on a range of devices/locations
