### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by Andy-ABTec** [Andy-ABTec/minimal-mistakes#4]
@MarkSummerville, I note yo have a 100% free mit license link on the home page.
Do you have have a license file specifically for tv rename?

**Comment by JoeBiellik** [comment]
I would recommend [linking to GH](https://github.com/TV-Rename/tvrename/blob/master/LICENSE.md).

**Comment by MarkSummerville** [comment]
No - this is a legacy of the prior Minimal-Mistakes site. As @JoeBiellik  says we should update to the correct licence type and link to it

**Comment by Andy-ABTec** [comment]
To be honest I was only following what I presume you'd put on the splash screen...

Do we really need a link and online license? - surely the license would be distributed with the software and an shown during installation and/or in "About" box in "Help" would give access to it.

**Comment by MarkSummerville** [comment]
Happy to remove the link also. We should reference the correct licence name though. The fact that TVR is free is still a key 'selling' point though

**Comment by Andy-ABTec** [comment]
Done (I think) just need some text to go under the graphics...

**Comment by MarkSummerville** [comment]
How about:

TV Rename is completely free to use. It is also open source, so if you wish to modify or enhance it for non-commercial use can. Although we'd request that you feedback any improvements into the project for others to benefit.

Link: https://github.com/TV-Rename/tvrename/blob/master/LICENSE.md

**Comment by Andy-ABTec** [comment]
That'll do nicely - ta!... 
I've updated the home page with a slightly tweaked version of the text, it looks better id all three paragraphs across the page are about the same length.
