### ISSUE TITLE
Proposed Update - Masthead Menu

### ISSUE THREAD

**Issue by Andy-ABTec** [Andy-ABTec/minimal-mistakes#7]
Having spent most of yesterday "playing" I think the attached "tweak" for the menu system is a huge step forward.

I can add it without changing the content of the template, it just needs a tweak to the custom javascript asset (already in place) to read the html file in (a new asset). Fallback will be a direct link from "The Manual" to user,html as it is now, but at least you'll get the option to jump to a specific chapter if scripting is enabled.
The content of the attached file should work as a standalone demo.
[menu-update.zip](https://github.com/Andy-ABTec/minimal-mistakes/files/1694576/menu-update.zip)

Thoughts?

@JoeBiellik, if you have time, would you mind having a poke at the css and jQuery just in case I've missed anything or there's a better way. It's been a while since I've written anything like this - witness it took me nearly all day!

**Comment by MarkSummerville** [comment]
Looks good. It’s looks part of the theme. Maybe create a pr to merge into the main template so everyone can use it?

**Comment by Andy-ABTec** [comment]
Its definitely NOT ready for that yet, I haven't even tested it in the theme yet!
