### ISSUE TITLE
Template support for wide pages

### ISSUE THREAD

**Issue by MarkSummerville** [Andy-ABTec/minimal-mistakes#8]
Hi, 

I noticed overnight the main template repo started supporting ‘wide’ pages which should like just the issue you were grappling with. Just thought i’d Mention it in case it cleans up some of your code

Cheers

**Comment by Andy-ABTec** [comment]
I picked it up earlier today...  My original change was no biggie - just a single line of "code" the template designer agreed with my solution a while ago though I doubt that's what he's done..

I need to double check whats actually changes,, at a quick glance there is still some CSS for a RH margin.
