### ISSUE TITLE
Ready for release?

### ISSUE THREAD

**Issue by MarkSummerville** [Andy-ABTec/minimal-mistakes#9]

**Comment by Andy-ABTec** [comment]
Me too = go for it...

**Comment by MarkSummerville** [comment]
To be honest I’m not sure how to release it. I was going to merge to tvrename/website#master and go from there. The old website content is in tvrename/tvrename#gh-pages. I’m hoping that it is just a cname change, but may need Steve to update again

**Comment by Andy-ABTec** [comment]
Should be ok, I think you just need to tweak any ab-tec references in config.yml and change the cname, everything else should fall into place.

If it falls in a heap just put the cname back and the current site will be restored (while investigating)

**Comment by Andy-ABTec** [comment]
Sneaking suspicion there's something amis in the repositories settings, but I don't have access to check.

Each repository can host one web site viz:

https://beta.tvrename.com - is in my minimal-mistakes repo and
https://andy-abtec.github.io/leap-day - is in my leap-day repo

So it can be done...

**Comment by MarkSummerville** [comment]
closing this as we have releaseed the site. Just need TVrename.com to be redirected
